<?php

namespace Crm\CaracteristicasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspecificacionesEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecificacionesEquipoRepository extends EntityRepository
{
}
