<?php

namespace Crm\CaracteristicasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemoriaRamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemoriaRamRepository extends EntityRepository
{
}
