<?php

namespace Crm\CaracteristicasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModeloEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeloEquipoRepository extends EntityRepository
{
}
