<?php

namespace crm\licenciaBundle\Entity;

/**
 * AvisosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisosRepository extends \Doctrine\ORM\EntityRepository
{
}
