<?php

namespace crm\licenciaBundle\Entity;

/**
 * CapacidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapacidadRepository extends \Doctrine\ORM\EntityRepository
{
}
