<?php

namespace crm\licenciaBundle\Entity;

/**
 * Direccion_fabricanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Direccion_fabricanteRepository extends \Doctrine\ORM\EntityRepository
{
}
