<?php

namespace crm\licenciaBundle\Entity;

/**
 * Direccion_personalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Direccion_personalRepository extends \Doctrine\ORM\EntityRepository
{
}
