<?php

namespace crm\licenciaBundle\Entity;

/**
 * Direccion_empresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Direccion_empresaRepository extends \Doctrine\ORM\EntityRepository
{
}
