<?php

namespace crm\licenciaBundle\Entity;

/**
 * Disco_duroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Disco_duroRepository extends \Doctrine\ORM\EntityRepository
{
}
