<?php

namespace crm\licenciaBundle\Entity;

/**
 * Licencia_equipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Licencia_equipoRepository extends \Doctrine\ORM\EntityRepository
{
}
