<?php

namespace crm\licenciaBundle\Entity;

/**
 * Memoria_ramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Memoria_ramRepository extends \Doctrine\ORM\EntityRepository
{
}
