<?php

namespace crm\licenciaBundle\Entity;

/**
 * PersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalRepository extends \Doctrine\ORM\EntityRepository
{
}
