<?php

namespace crm\licenciaBundle\Entity;

/**
 * ProcedenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcedenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
