<?php

namespace crm\licenciaBundle\Entity;

/**
 * ProcesadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesadorRepository extends \Doctrine\ORM\EntityRepository
{
}
