<?php

namespace crm\licenciaBundle\Entity;

/**
 * Tipo_licenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tipo_licenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
