<?php

namespace Crm\ClienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
	public function cliente($id)
	{
		return $this->getEntityManager()->createQuery('SELECT c, dc FROM ClienteBundle:DireccionCliente dc JOIN dc.cliente c WHERE c.id = :id')->setParameter('id',$id)->getResult();
	}
}
