<?php

namespace Crm\ClienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RangoClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangoClienteRepository extends EntityRepository
{
}
