<?php

namespace Crm\UsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AvisosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisosRepository extends EntityRepository
{
}
