producto_producto:
    resource: "@ProductoBundle/Resources/config/routing/producto.yml"
    prefix:   /producto

producto_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProductoBundle:Default:index }
