Crm\ProductoBundle\Entity\Producto:
    type: entity
    table: null
    repositoryClass: Crm\ProductoBundle\Entity\ProductoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '30'
    oneToMany:
        termino:
            targetEntity: Crm\ProductoBundle\Entity\Termino
            mappedBy: Producto
    lifecycleCallbacks: {  }
