<?php

namespace Crm\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComentariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentariosRepository extends EntityRepository
{
	public function comentarioTicket($id)
	{
		return $this->getEntityManager()->createQuery('SELECT c AS comentario, u.userName AS usuario FROM TicketBundle:Comentarios c, UsuariosBundle:Usuarios u WHERE c.usuarioCreo = u.id AND c.ticket = :id' )->setParameter('id',$id)->getResult();
	}

}
