<?php

namespace Crm\PersonalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DireccionPersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionPersonalRepository extends EntityRepository
{
}
