<?php

namespace Crm\PersonalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalRepository extends EntityRepository
{
	public function email($id)
	{
		return $this->getEntityManager()->createQuery('SELECT p FROM PersonalBundle:Personal p, UsuariosBundle:Avisos a INNER JOIN a.usuarios u WHERE p.id = u.personal AND a.usuarios = :id ')->setParameter('id',$id)->getResult(); 
	}
}
