<?php

namespace Crm\FabricanteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FabricanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabricanteRepository extends EntityRepository
{
}
