<?php

namespace Crm\FabricanteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FabricanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabricanteRepository extends EntityRepository
{
	public function fabricante($id)
	{
		return $this->getEntityManager()->createQuery('SELECT f, df FROM FabricanteBundle:DireccionFabricante df JOIN df.fabricante f WHERE f.id = :id')->setParameter('id',$id)->getResult();
	}
}
