ventas_venta:
    resource: "@VentasBundle/Resources/config/routing/venta.yml"
    prefix:   /venta

ventas_homepage:
    path:     /hello/{name}
    defaults: { _controller: VentasBundle:Default:index }

venta_send:
    path: /send
    defaults: {_controller: VentasBundle:Venta:send }
