caracteristicas_modeloequipo:
    resource: "@CaracteristicasBundle/Resources/config/routing/modeloequipo.yml"
    prefix:   /modeloequipo

caracteristicas_versionsoftware:
    resource: "@CaracteristicasBundle/Resources/config/routing/versionsoftware.yml"
    prefix:   /versionsoftware

caracteristicas_procesador:
    resource: "@CaracteristicasBundle/Resources/config/routing/procesador.yml"
    prefix:   /procesador

caracteristicas_memoriaram:
    resource: "@CaracteristicasBundle/Resources/config/routing/memoriaram.yml"
    prefix:   /memoriaram

caracteristicas_discoduro:
    resource: "@CaracteristicasBundle/Resources/config/routing/discoduro.yml"
    prefix:   /discoduro

caracteristicas_dimenciones:
    resource: "@CaracteristicasBundle/Resources/config/routing/dimenciones.yml"
    prefix:   /dimenciones

caracteristicas_homepage:
    path:     /hello/{name}
    defaults: { _controller: CaracteristicasBundle:Default:index }
