caracteristicas_modeloequipo:
    resource: "@CaracteristicasBundle/Resources/config/routing/modeloequipo.yml"
    prefix:   warriors/modeloequipo

caracteristicas_versionsoftware:
    resource: "@CaracteristicasBundle/Resources/config/routing/versionsoftware.yml"
    prefix:   warriors/versionsoftware

caracteristicas_procesador:
    resource: "@CaracteristicasBundle/Resources/config/routing/procesador.yml"
    prefix:   warriors/procesador

caracteristicas_memoriaram:
    resource: "@CaracteristicasBundle/Resources/config/routing/memoriaram.yml"
    prefix:   warriors/memoriaram

caracteristicas_discoduro:
    resource: "@CaracteristicasBundle/Resources/config/routing/discoduro.yml"
    prefix:   warriors/discoduro

caracteristicas_dimensiones:
    resource: "@CaracteristicasBundle/Resources/config/routing/dimensiones.yml"
    prefix:   warriors/dimensiones

caracteristicas_homepage:
    path:     /hello/{name}
    defaults: { _controller: CaracteristicasBundle:Default:index }
