security:
    encoders:
        Crm\UsuariosBundle\Entity\Usuarios: 
            algorithm: bcrypt
            #algorithm: bcrypt
            #cost : 7
        Symfony\Component\Security\Core\User\User: #plaintext
            algorithm: bcrypt
            cost: 7

    role_hierarchy:
        ROLE_VENTAS:        ROLE_VENTAS
        ROLE_SOPORTE:       ROLE_SOPORTE
        ROLE_SUPER_ADMIN:   [ROLE_ALLOWED_TO_SWITCH, ROLE_VENTAS,ROLE_SOPORTE]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, Usuario]
        in_memory:
            memory:
                users:
                    # NOTA: UNA VEZ PUESTO EL PROYECTO EN PRODUCCION, NO SE DEBE CAMBIAR NINGUNO DE LOS VALORES SIGUIENTES:
                    developer:
                        password: $2a$07$m2L.9HVxC0Y0bSzFTK5DoeXyQOTRfhPk6uyox2gvGIktpCRmYph9m
                        #dev
                        roles: 'ROLE_SUPER_ADMIN'
        Usuario:
            entity:
                class: UsuariosBundle:Usuarios

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        login_firewall:
            pattern: ^/login$
            anonymous: ~

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: /logout
                target: /login
            remember_me:
                key: holysoymuyseguro
                lifetime: 1800

        main:
            http_basic: ~
            stateless: true

        default:
            pattern: ^/
            http_basic: ~
            provider: Usuario
            #anonymous: ~
    access_control:
    # NOTA: LAS RESTRICCIONES DE ACCESO TAMBIÉN ESTÁN DECLARADAS EN LOS CONTROLADORES
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/venta/*, roles: [ROLE_VENTAS,ROLE_SUPER_ADMIN] }
    - { path: ^/warriors/*, roles: [ROLE_SOPORTE,ROLE_SUPER_ADMIN] }
    - { path: ^/*, roles: [ROLE_SOPORTE,ROLE_SUPER_ADMIN,ROLE_VENTAS] }

