<?php

namespace Crm\EmpresaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{
	public function empresa($id)
	{
		return $this->getEntityManager()->createQuery('SELECT e, de FROM EmpresaBundle:DireccionEmpresa de JOIN de.empresa e WHERE e.id = :id')->setParameter('id',$id)->getResult();
	}
}
