Crm\EmpresaBundle\Entity\DireccionEmpresa:
    type: entity
    table: null
    repositoryClass: Crm\EmpresaBundle\Entity\DireccionEmpresaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        calle:
            type: string
            length: '50'
        numeroExt:
            type: string
            length: '10'
            column: numero_ext
        numeroInt:
            type: string
            length: '10'
            column: numero_int
            nullable: TRUE
        colonia:
            type: string
            length: '50'
        codigoPostal:
            type: string
            column: codigo_postal
            length: '5'
        localidad: 
            type: string
            length: '50'
    manyToOne:
        empresa:
          targetEntity: Crm\EmpresaBundle\Entity\Empresa
          cascade: [persist]
          inversedBy: direccionEmpresa
          joinColumn:
                name: empresa_id
                referencedColumnName: id
                onDelete: CASCADE
        municipio:
          targetEntity: Crm\GeneralBundle\Entity\Municipio
          inversedBy: direccionEmpresa
          joinColumn:
                name: municipio_id
                referencedColumnName: id
        estado:
          targetEntity: Crm\GeneralBundle\Entity\Estado
          inversedBy: direccionEmpresa
          joinColumn:
                name: estado_id
                referencedColumnName: id
        pais:
          targetEntity: Crm\GeneralBundle\Entity\Pais
          inversedBy: direccionEmpresa
          joinColumn:
                name: pais_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
