<?php

namespace Crm\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstatusRepository extends EntityRepository
{
}
