Crm\CaracteristicasBundle\Entity\Dimensiones:
    type: entity
    table: null
    repositoryClass: Crm\CaracteristicasBundle\Entity\DimensionesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dimensiones:
            type: string
            length: '25'
    oneToMany:
        caracteristicasEquipo: 
           targetEntity: Crm\EquipoBundle\Entity\CaracteristicasEquipo
           mappedBy: Dimensiones 
    lifecycleCallbacks: {  }
