Crm\CaracteristicasBundle\Entity\Procesador:
    type: entity
    table: null
    repositoryClass: Crm\CaracteristicasBundle\Entity\ProcesadorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        marca:
            type: string
            length: '20'
        modelo:
            type: string
            length: '30'
        velocidad:
            type: string
            length: '4'
        unidad:
            type: string
            length: '10'
        terminoProcesador:
            type: string
            length: '20'
    oneToMany:
        caracteristicasEquipo: 
            targetEntity: Crm\EquipoBundle\Entity\CaracteristicasEquipo
            mappedBy: Procesador
    lifecycleCallbacks: {  }
