Crm\CaracteristicasBundle\Entity\VersionSoftware:
    type: entity
    table: null
    repositoryClass: Crm\CaracteristicasBundle\Entity\VersionSoftwareRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        versionSoftware:
            type: string
            length: '50'
            column: version_software
    lifecycleCallbacks: {  }
