Crm\PersonalBundle\Entity\Personal:
    type: entity
    table: null
    repositoryClass: Crm\PersonalBundle\Entity\PersonalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '20'
        apePat:
            type: string
            length: '30'
            column: ape_pat
        apeMat:
            type: string
            length: '30'
            column: ape_mat
        telefono:
            type: string
            length: '15'
            nullable: true
        celular:
            type: string
            length: '15'
            nullable: true
        email:
            type: string
            length: '50'
    manyToOne:
        estatus:
            targetEntity: Crm\GeneralBundle\Entity\Estatus
            inversedBy: personal
            joinColumn:
                name: estatus_id
                referencedColumnName: id
        empresa:
            targetEntity: Crm\EmpresaBundle\Entity\Empresa
            inversedBy: personal
            joinColumn:
                name: empresa_id
                referencedColumnName: id
        puesto:
            targetEntity: Crm\PersonalBundle\Entity\Puesto
            inversedBy: personal
            joinColumn:
                name: puesto_id
                referencedColumnName: id
    oneToMany:
        equipo:
            targetEntity: Crm\EquipoBundle\Entity\Equipo
            mappedBy: Personal
        direccionPersonal:
            targetEntity: Crm\PersonalBundle\Entity\DireccionPersonal
            mappedBy: Personal
    oneToOne:
        usuarios:
            targetEntity: Crm\UsuariosBundle\Entity\Usuarios
            inversedBy: personal
            joinColumn:
              name: usuarios_id
              referencedColumnName: id
    lifecycleCallbacks: {  }
