Crm\FabricanteBundle\Entity\Fabricante:
    type: entity
    table: null
    repositoryClass: Crm\FabricanteBundle\Entity\FabricanteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        razonSocial:
            type: string
            length: '50'
            column: razon_social
        rfc:
            type: string
            length: '15'
        telefono1:
            type: string
            length: '15'
            column: telefono_1
        ext1:
            type: integer
            column: ext_1
            nullable: TRUE
        telefono2:
            type: string
            length: '15'
            column: telefono_2
            nullable: TRUE
        ext2:
            type: integer
            column: ext_2
            nullable: TRUE
        email:
            type: string
            length: '50'
        paginaWeb:
            type: string
            length: '50'
            column: pagina_web
            nullable: TRUE
    manyToOne:
        estatus:
          targetEntity: Crm\GeneralBundle\Entity\Estatus
          inversedBy: fabricante
          joinColumn:
              name: estatus_id
              referencedColumnName: id
    oneToMany:
        direccionFabricante: 
          targetEntity: Crm\FabricanteBundle\Entity\DireccionFabricante  
          mappedBy: Fabricante
        equipo:
            targetEntity: Crm\EquipoBundle\Entity\Equipo
            mappedBy: Fabricante
    lifecycleCallbacks: {  }
