Crm\VentasBundle\Entity\Venta:
    type: entity
    table: null
    repositoryClass: Crm\VentasBundle\Entity\VentaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fechaVenta:
            type: datetime
            column: fecha_venta
        estatus:
            type: string
            length: '20'
    manyToOne:
        usuarios:
          targetEntity: Crm\UsuariosBundle\Entity\Usuarios
          inversedBy: venta
          joinColumn:
              name: usuarios_id
              referencedColumnName: id
        producto:
          targetEntity: Crm\ProductoBundle\Entity\Producto
          inversedBy: venta
          joinColumn:
            name: producto_id
            referencedColumnName: id
        cliente:
          targetEntity: Crm\ClienteBundle\Entity\Cliente
          inversedBy: venta
          joinColumn: 
            name: cliente_id
            referencedColumnName: id
        equipo:
          targetEntity: Crm\EquipoBundle\Entity\Equipo
          inversedBy: venta
          joinColumn:
            name: equipo_id
            referencedColumnName: id
    lifecycleCallbacks: {  }