<?php

namespace Crm\EquipoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends EntityRepository
{
	public function equiposLibres($serial)
	{
		return $this->getEntityManager()->createQuery("SELECT equipo FROM EquipoBundle:Equipo equipo WHERE equipo.serieWarriors = :serie")->setParameter('serie', $serial)->getResult();
	}
}
