<?php

namespace Crm\EquipoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LicenciaEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenciaEquipoRepository extends EntityRepository
{
}
