<?php

namespace Crm\EquipoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProcedenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcedenciaRepository extends EntityRepository
{
}
