equipo_ubicacion:
    resource: "@EquipoBundle/Resources/config/routing/ubicacion.yml"
    prefix:   /ubicacion

equipo_licenciaequipo:
    resource: "@EquipoBundle/Resources/config/routing/licenciaequipo.yml"
    prefix:   /licenciaequipo

equipo_equipo:
    resource: "@EquipoBundle/Resources/config/routing/equipo.yml"
    prefix:   /equipo

equipo_homepage:
    path:     /hello/{name}
    defaults: { _controller: EquipoBundle:Default:index }
